### ISSUE TITLE
not working for ng-minLength and ng-required

### ISSUE THREAD

**Issue by phuyem** [angular-ui/ui-tinymce#151] opened 2015-07-16 09:31 UTC
Hello,
Adding ng-minLength and ng-required (not tested with other angular validation) will break ng-model

Thanks

**Comment by deeg** [comment] 2015-10-16 01:47
Please update the issue with a Plunker or Fiddle re-creating.

**Comment by deeg** [comment] 2015-10-20 05:19
Closing this ticket as a duplicate of #145. I will add min-length to that ticket.

Ng-required alone should be fixed now. Thanks for reporting.

**Closed by deeg** 2015-10-20 05:19 UTC
Labels: duplicate, needs plunker
