### ISSUE TITLE
Pasting text does not change the model

### ISSUE THREAD

**Issue by MrMartiniMo** [angular-ui/ui-tinymce#247] opened 2016-04-23 20:44 UTC
Hi there!

I've found that the model does not change, if I past text into the tinymce input.
I try to analyze the problem.

https://plnkr.co/edit/YRfHj2EpWldiH1856CxK?p=preview

**Comment by MrMartiniMo** [comment] 2016-04-23 21:19
I figured out that tinymce doesn't change the dirty flag by pasting text, unless the "past" plugin is loaded. 
https://plnkr.co/edit/2Q1KfaUdh77XutpuhzsP?p=preview

So you think thats a bug in tinymce? Anyway, it is not an error in ui-tinimce!

**Comment by deeg** [comment] 2016-04-28 20:18
Closing as a duplicate of #240

**Closed by deeg** 2016-04-28 20:18 UTC
