### ISSUE TITLE
Validation for `ngMaxlength` and `ngMinlength` is not working on TinyMCE input with SCE enabled

### ISSUE THREAD

**Issue by naXa777** [angular-ui/ui-tinymce#227] opened 2016-02-05 13:49 UTC
<textarea ng-model="myMCEContent" ui-tinymce ng-maxlength="180" name="body"></textarea>

I have created this `<textarea>` but `ngMaxlength` and `ngMinlength` are not working. For example when I typed just a single character the textarea became invalid. Then I've found that the directives work if I disable Strict Contextual Escaping. However, this is strongly discouraged.
Example in jsFiddle: https://jsfiddle.net/naXa/zsnLupvd/ (try to enter some text in textarea to see an error message, then enable `$sceProvider`, rerun, clear all text, and try typing again)

I use [TinyMCE ](https://www.tinymce.com/) and [AngularUI wrapper for TinyMCE](https://github.com/angular-ui/ui-tinymce).

Why are `ngMaxlength` and `ngMinlength` not working in this case? And how to fix it?

**Comment by deeg** [comment] 2016-02-05 14:41
Closing this as a duplicate of #145.

If you have any solutions please feel free to put out a PR. I will continue looking into it.

**Closed by deeg** 2016-02-05 14:41 UTC
