### ISSUE TITLE
'setAttribute' of undefined

### ISSUE THREAD

**Issue by ashishtilara** [angular-ui/ui-tinymce#217] opened 2016-01-18 11:13 UTC
I am building a wizard and editor comes on 2nd page, so if someone tries to access 2nd page, I have code to move to step1 like `$location.path("/step1");` but I get 

```
Uncaught TypeError: Cannot read property 'setAttribute' of undefined
```

in `aria` function of tinymce at following line:

```
elm.setAttribute(name == 'role' ? name : 'aria-' + name, value);
```

Appreciate any help to fix this.

cheers

**Comment by deeg** [comment] 2016-01-19 01:36
Can you please post a Plunker reproducing the issue so we can better look into fixing it?

**Comment by ashishtilara** [comment] 2016-01-19 09:47
here we go, http://embed.plnkr.co/Dtm6nkf9cutEwOiXuQc5/

If you click on step 2, it should go to step1 but will show that error

**Comment by deeg** [comment] 2016-01-19 14:50
Oh this is an error in TinyMCE code. I will take a look to see if this is being caused by our library.

**Comment by ashishtilara** [comment] 2016-01-20 04:52
Yeah, the error is only happening when the rendering process is half way and the template changes.

**Comment by clonitza** [comment] 2016-03-14 14:37
A workaround until a fix comes, add/remove event handlers as needed, I'm using ui router in my app:

```
var locationChangeStartHandler = $scope.$on("$locationChangeStart", function(event){
	event.preventDefault();
});

var stateChangeStartHandler = $scope.$on("$stateChangeStart", function(event){
	event.preventDefault();
});

tinymceOptions = {
	setup: function (editor) {
		editor.on("init", function () {
			/* Editor needs to be fully rendered to the page before removing the event handlers 
			Fiddle with the timeout value if needed. */
			$timeout(function(){
				locationChangeStartHandler();
				locationChangeStartHandler = null;
				stateChangeStartHandler();
				stateChangeStartHandler = null;
			},500);
		});
	},
	...
}
```

If you find other ways to remove the handlers without using the timeout please do tell.

**Comment by RangaKom** [comment] 2016-04-04 18:29
I am getting "locationChangeStartHandler is not a function" Error

**Comment by KreepN** [comment] 2016-06-01 19:22
I'm in the same boat as the original poster that I am using ui-tinymce in a wizard that contains multiple states ( using "ui.router"). It would seem that this is still an issue, although one affecting a minority of people. Is there anyway to prevent the directive from resolving if it is aware of a state change on progress?

**Comment by dfabreguette-ap** [comment] 2016-08-25 09:22
+1

**Comment by jelgblad** [comment] 2016-08-30 05:02
+1

**Comment by scottieslg** [comment] 2016-10-03 17:34
Changing this code fixed it for me:

function ensureInstance() {
    if (!tinyInstance) {
        tinyInstance = tinymce.get(attrs.id);
    }
}

to:

function ensureInstance() {
    if (!tinyInstance) {
        $timeout(function() {
            tinyInstance = tinymce.get(attrs.id);
        });
    }
}

**Comment by gyulakrizsma** [comment] 2016-11-02 07:49
Changing this part of the `tinymce.js`:

```

**Comment by deeg** [comment] 2016-12-16 18:39
@gyulakrizsma's change should already be in the latest release. Going to close this as should not be an issue any more. Please let me know if you are still seeing issues with latest version and we can re-open.

**Closed by deeg** 2016-12-16 18:39 UTC
Labels: needs investigation
