### ISSUE TITLE
dialog boxes and error dialog do not appear correctly.

### ISSUE THREAD

**Issue by psarda** [angular-ui/ui-tinymce#196] opened 2015-11-26 06:30 UTC
I am using the ui-tinymce with ui-bootstrap. The dialog boxes and error-dialog which are launched by tinymce editor are not appearing well formatted.

codepen: http://codepen.io/ParagSarda/pen/WQqoVr?editors=100

**Comment by deeg** [comment] 2015-11-28 21:10
This library does not supply any CSS files. This is just meant to be an angular wrapper around the TinyMCE library.

The issues you are facing are CSS based and should be fixed by isolating the rules which is messing things up, and overwriting those rules for the TinyMCE case.

The example you have doesn't load, it looks like TinyMCE updated its website and in turn list of hosted plugins and not all the ones the demo supplies is there. Removing everything but image makes it work and the dialog boxes seem fine to be.

Going to close this ticket as not an issue with this library, if you have any other reproducible bugs, please feel free to open another issue.

**Closed by deeg** 2015-11-28 21:10 UTC

**Comment by psarda** [comment] 2015-11-28 23:14
Thanks @deeg for explanation.
