### ISSUE TITLE
Some toolbar buttons don't work. They don't even get added to the editor.

### ISSUE THREAD

**Issue by mascip** [angular-ui/ui-tinymce#57] opened 2013-11-26 20:31 UTC
I try to use these options:
    $scope.tinymceOptions =
        menubar: false
        statusbar: false
        toolbar: "redo undo | styleselect | bold italic | spellchecker link image | save"
But several buttons of the toolbar aren't even visible. I see the first 5 buttons, but not the last 4 ones. If I change the order of the buttons, the problem is the same.

**Comment by wesleycho** [comment] 2015-06-05 21:52
Closing as I am not able to reproduce this and was able to successfully load plugins by using the `plugins` option as @grantgeorge mentioned.

**Closed by wesleycho** 2015-06-05 21:52 UTC
