### ISSUE TITLE
How to load ui-tinymce programmatically

### ISSUE THREAD

**Issue by vutaviva** [angular-ui/ui-tinymce#235] opened 2016-02-24 02:01 UTC
I want load ui-tinymce in div programmatically when user click on this div. It means I want delay loading until user interact with element. Can I do that?

**Comment by deeg** [comment] 2016-02-24 17:20
Are you trying to use tinymce in inline mode with the div being the container to invoke tinymce on?

If so why not just have it loaded when the page loads?

You could instantiate a tinymce directive on click though, by putting an ng-if on the directive with a variable that gets set to true when the correct location on the page is clicked.

Going to close this issue as it is not a bug or feature request, but feel free to respond back and I can help you more here if needed.

**Closed by deeg** 2016-02-24 17:20 UTC
Labels: question
