### ISSUE TITLE
ID_ATTR  gets duplicated

### ISSUE THREAD

**Issue by hakanostrom** [angular-ui/ui-tinymce#304] opened 2016-11-03 13:14 UTC
In the last update (0.0.17) the ID_ATTR  is based on a timestamp. This causes duplicated id:s when two or more tags are created within the same timeframe.
In previous versions it was based on an incremented value ware the issue newer occoured.
What was the reason of the change?

**Comment by rbecheras** [comment] 2016-11-03 15:46
This is a duplicate of #295

**Closed** 2016-12-16 18:20 UTC
